#!/bin/python3

import json
import os
import subprocess

with open('/home/ramel/.todos.json') as file:
    js = json.load(file)

task_list = [e['subject'] for e in js] 
ind_list = [i['id'] for i in js]
x = '\n'.join(task_list)

cmd = "echo \'{0}\'| dmenu -g 1 -l 10 -n".format(x)

task = subprocess.check_output(cmd, shell=True)
task = task.decode('utf8').rstrip('\n')


try:
    ind = task_list.index(task)
    z = ind_list[ind]
    os.system('ultralist delete {0}'.format(z))
except:
    try:
        os.system('ultralist add {0}'.format(task))
    except:
        pass

os.system("ultralist ar gc")








 


