#!/bin/bash

echo $1

if [ $1 == "high" ]; then
	xrandr --output DVI-D-0 --brightness 1 &&
	xrandr --output HDMI-0 --brightness 1
fi

if [ $1 == "medium" ]; then
	xrandr --output DVI-D-0 --brightness .75 &&
	xrandr --output HDMI-0 --brightness .75
fi

if [ $1 == "low" ]; then
	xrandr --output DVI-D-0 --brightness .50 &&
	xrandr --output HDMI-0 --brightness .50
fi
	
dunstify -a "changeBrightness" -u low "Brightness: $1" -t 700 &
canberra-gtk-play -i audio-volume-change 

