#!/bin/bash
# changeVolume

# Arbitrary but unique message id
msgId="991049"

# Change the volume using alsa(might differ if you use pulseaudio)
amixer set Master "$@" > /dev/null

# Query amixer for the current volume and whether or not the speaker is muted
vol="$(amixer get Master | tail -1 | awk -F ' ' '{print $0, $(NF-1)}' | sed 's/[^0-9]*//g')"
volume=${vol: -2}
mute="$(amixer get Master | tail -1 | awk '{print $6}' | sed 's/[^a-z]*//g')"
if [[ $volume == 0 || "$mute" == "off"  ]]; then
    # Show the sound muted notification
    dunstify -a "changeVolume" -u low -i audio-volume-muted -r "$msgId" "Volume muted" -t 900
else
    # Show the volume notification
    dunstify -a "changeVolume" -u low -i audio-volume-high -r "$msgId" -t 1000 \
    -h int:value:"$volume" "Volume: ${volume}%" -t 900
fi

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
