#!/bin/python3
import json
import subprocess, os
import datetime

def main():
    with open('/home/ramel/.todoist.cache.json') as file:

        js = json.load(file)

    task_list = []
    ind_list = []
    today = datetime.datetime.now()
    task = ""

    count = 0;
    for z in js["items"]:
        if z['due'] != 'none':
            ind_list.append(z['id'])
            content = str(z['content'])
            due = z['due'] #['date']
            try:
                due_date = due['date']
            except:
                due_due = ""
            choice = due_date +  " | " + content 
            if count < 5:
                count = count + 1
                task_list.append(choice)

    x = '\n'.join(sorted(task_list))
    print(x)
    dmenu_cmd = "dmenu -g 1 -l 10 -sf '#12100E' -sb '#FB676E' -i -p"
    cmd = "echo \"{0}\" | {1} Task:".format(x, dmenu_cmd)

    task = subprocess.check_output(cmd, shell=True)
    task = task.decode('utf8').rstrip('\n')

    try:
        ind = task_list.index(task)
        z = ind_list[ind]
        os.system("todoist d {0}".format(z))
    except:
        addTodo(task, dmenu_cmd)

    return 0

def addTodo(task, dmenu_cmd):
    get_project = "todoist projects | " + dmenu_cmd + " 'Project:'"
    project = subprocess.check_output(get_project, shell=True).decode('utf8').rstrip('\n')
    try: 
        get_due_date = "echo 'today\ntomorrow\nnext week' | " + dmenu_cmd + " 'Due Date:'"
    except: 
        get_due_date = ""
    due_date = subprocess.check_output(get_due_date, shell=True).decode('utf8').rstrip('\n')
    subprocess.check_output("todoist add \"{0}\" -P \"{1}\" -d \"{2}\" & todoist sync".format(task, project[0], due_date), shell=True)


if __name__ == "__main__":
    main()




     


