#!/bin/python3

import json
import os
import subprocess

with open('/home/ramel/.todos.json') as file:
    js = json.load(file)

task_list = []
ind_list = []
for z in js:
    if z['archived'] == False:
        task_list.append(z['subject'])
        ind_list.append(z['id'])
        # task_list = [i['subject'] for i in js] 
        # ind_list = [i['id'] for i in js]

x = '\n'.join(task_list)
cmd = "echo \'{0}\'| dmenu -g 1 -l 10 -sf '#12100E' -sb '#FB676E' -i -p 'task:'".format(x)

task = subprocess.check_output(cmd, shell=True)
task = task.decode('utf8').rstrip('\n')

try:
    ind = task_list.index(task)
    z = ind_list[ind]
except:
    try:
        os.system('ultralist add {0}'.format(task))
    except:
        pass








 


