#!/bin/python3
import time
import os, subprocess

date = time.strftime("%m-%d-%Y")
date_time = date + time.strftime("%H:%M")
title = "note-" + date + ".md"
path = "/home/ramel/notes/"
os.system("touch " + path + title)

ls = subprocess.check_output("ls " + path, shell=True).decode('utf-8')
entry = subprocess.check_output("ls /home/ramel/notes/ | dmenu -p 'Prompt' -l 1 -g 1", 
        shell=True).decode('utf-8')

if entry not in ls:
    with open(path + title, 'a') as file:
        file.write("# "+date_time+"\n")
        file.write(entry)
else:
    os.system("alacritty -e vim /home/ramel/notes/" + entry)
    


