#!/bin/sh

latestNotefile="$HOME/notes/note-$(date +%m-%d-%Y).md"

if [ ! -f $latestNotefile ]; then
	echo "# Notes for $(date +%m-%d-%Y)" > $latestNotefile
fi

vim -c "norm Go## $(date +%H:%M)" \
	-c "norm Go" \
	-c "startinsert" $latestNotefile



